=== SHombert/TP_DW/info.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT information (act)*>

<!ELEMENT act (sc)+>
<!ATTLIST act nom CDATA #REQUIRED>

<!ELEMENT sc EMPTY>
<!ATTLIST sc
  nom CDATA #REQUIRED
  sort (adopté|rejeté) #REQUIRED date CDATA #REQUIRED
  mandat CDATA #REQUIRED grp CDATA #REQUIRED
  présent (Oui|Nom) #REQUIRED>

=== SHombert/TP_DW/src/sortieSax.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE information SYSTEM "info.dtd">
<information>
<act nom = "Abadie Caroline">
</act>
<act nom = "Abba Bérangère">
</act>
<act nom = "Adam Damien">
</act>
<act nom = "Adam Lénaïck">
</act>
<act nom = "Ahamada Saïd">
</act>
<act nom = "Alauzet Éric">
</act>
<act nom = "Ali Ramlati">
</act>
<act nom = "Aliot Louis">
</act>
<act nom = "Amadou Aude">
</act>
<act nom = "Anato Patrice">
</act>
<act nom = "André François">
</act>
<act nom = "Anglade Pieyre-Alexandre">
</act>
<act nom = "Anthoine Emmanuelle">
</act>
<act nom = "Ardouin Jean-Philippe">
</act>
<act nom = "Arend Christophe">
</act>
<act nom = "Attal Gabriel">
</act>
<act nom = "Avia Laetitia">
</act>
<act nom = "Aviragnet Joël">
</act>
<act nom = "Bachelier Florian">
</act>
<act nom = "Bagarry Delphine">
</act>
<act nom = "Baichère Didier">
</act>
<act nom = "Balanant Erwan">
</act>
<act nom = "Bannier Géraldine">
</act>
<act nom = "Barbier Frédéric">
</act>
<act nom = "Barrot Jean-Noël">
</act>
<act nom = "Batut Xavier">
</act>
<act nom = "Baudu Stéphane">
</act>
<act nom = "Bazin Thibault">
</act>
<act nom = "Bazin-Malgras Valérie">
</act>
<act nom = "Beaudouin-Hubiere Sophie">
</act>
<act nom = "Beauvais Valérie">
</act>
<act nom = "Belhaddad Belkhir">
</act>
<act nom = "Belhamiti Mounir">
</act>
<act nom = "Benin Justine">
</act>
<act nom = "Bergé Aurore">
</act>
<act nom = "Bernalicis Ugo">
</act>
<act nom = "Berta Philippe">
</act>
<act nom = "Berville Hervé">
</act>
<act nom = "Besson-Moreau Grégory">
</act>
<act nom = "Bessot Ballot Barbara">
</act>
<act nom = "Bilde Bruno">
</act>
<act nom = "Blanc Anne">
</act>
<act nom = "Blanchet Christophe">
</act>
<act nom = "Blein Yves">
</act>
<act nom = "Bois Pascal">
</act>
<act nom = "Bolo Philippe">
</act>
<act nom = "Bonnell Bruno">
</act>
<act nom = "Bono-Vandorme Aude">
</act>
<act nom = "Bony Jean-Yves">
</act>
<act nom = "Borowczyk Julien">
</act>
<act nom = "Bothorel Éric">
</act>
<act nom = "Bouchet Jean-Claude">
</act>
<act nom = "Boudié Florent">
</act>
<act nom = "Bourguignon Brigitte">
</act>
<act nom = "Bourlanges Jean-Louis">
</act>
<act nom = "Bournazel Pierre-Yves">
</act>
<act nom = "Bouyx Bertrand">
</act>
<act nom = "Boyer Pascale">
</act>
<act nom = "Braun-Pivet Yaël">
</act>
<act nom = "Breton Xavier">
</act>
<act nom = "Bricout Jean-Louis">
</act>
<act nom = "Bridey Jean-Jacques">
</act>
<act nom = "Brocard Blandine">
</act>
<act nom = "Bru Vincent">
</act>
<act nom = "Brugnera Anne">
</act>
<act nom = "Brulebois Danielle">
</act>
<act nom = "Brun Fabrice">
</act>
<act nom = "Brunet Anne-France">
</act>
<act nom = "Buchou Stéphane">
</act>
<act nom = "Bureau-Bonnard Carole">
</act>
<act nom = "Cabaré Pierre">
</act>
<act nom = "Calvez Céline">
</act>
<act nom = "Cariou Émilie">
</act>
<act nom = "Cattelot Anne-Laure">
</act>
<act nom = "Cattin Jacques">
</act>
<act nom = "Causse Lionel">
</act>
<act nom = "Cazarian Danièle">
</act>
<act nom = "Cazebonne Samantha">
</act>
<act nom = "Cazeneuve Jean-René">
</act>
<act nom = "Cazenove Sébastien">
</act>
<act nom = "Cellier Anthony">
</act>
<act nom = "Cesarini Jean-François">
</act>
<act nom = "Chalas Émilie">
</act>
<act nom = "Chalumeau Philippe">
</act>
<act nom = "Chapelier Annie">
</act>
<act nom = "Charrière Sylvie">
</act>
<act nom = "Charvier Fannette">
</act>
<act nom = "Chassaing Philippe">
</act>
<act nom = "Chenu Sébastien">
</act>
<act nom = "Cherpion Gérard">
</act>
<act nom = "Chiche Guillaume">
</act>
<act nom = "Christophe Paul">
</act>
<act nom = "Cinieri Dino">
</act>
<act nom = "Ciotti Éric">
</act>
<act nom = "Claireaux Stéphane">
</act>
<act nom = "Clapot Mireille">
</act>
<act nom = "Cloarec-Le Nabour Christine">
</act>
<act nom = "Clément Jean-Michel">
</act>
<act nom = "Colas-Roy Jean-Charles">
</act>
<act nom = "Colboc Fabienne">
</act>
<act nom = "Coquerel Éric">
</act>
<act nom = "Corbière Alexis">
</act>
<act nom = "Cordier Pierre">
</act>
<act nom = "Cormier-Bouligeon François">
</act>
<act nom = "Corneloup Josiane">
</act>
<act nom = "Couillard Bérangère">
</act>
<act nom = "Crouzet Michèle">
</act>
<act nom = "Cubertafon Jean-Pierre">
</act>
<act nom = "Da Silva Dominique">
</act>
<act nom = "Dalloz Marie-Christine">
</act>
<act nom = "Damaisin Olivier">
</act>
<act nom = "Daniel Yves">
</act>
<act nom = "Dassault Olivier">
</act>
<act nom = "David Dominique">
</act>
<act nom = "Degois Typhanie">
</act>
<act nom = "Delatte Marc">
</act>
<act nom = "Delatte Rémi">
</act>
<act nom = "Delpon Michel">
</act>
<act nom = "Deprez-Audebert Marguerite">
</act>
<act nom = "Descamps Béatrice">
</act>
<act nom = "Descoeur Vincent">
</act>
<act nom = "Descrozaille Frédéric">
</act>
<act nom = "Dharréville Pierre">
</act>
<act nom = "Di Pompeo Christophe">
</act>
<act nom = "Dirx Benjamin">
</act>
<act nom = "Dive Julien">
</act>
<act nom = "Djebbari Jean-Baptiste">
</act>
<act nom = "Do Stéphanie">
</act>
<act nom = "Dombreval Loïc">
</act>
<act nom = "Dubois Jacqueline">
</act>
<act nom = "Dubost Coralie">
</act>
<act nom = "Dubré-Chirat Nicole">
</act>
<act nom = "Dufeu Schubert Audrey">
</act>
<act nom = "Dufrègne Jean-Paul">
</act>
<act nom = "Dumas Françoise">
</act>
<act nom = "Dumas Frédérique">
</act>
<act nom = "Dumont Pierre-Henri">
</act>
<act nom = "Dupont Stella">
</act>
<act nom = "Dupont-Aignan Nicolas">
</act>
<act nom = "Duvergé Bruno">
</act>
<act nom = "Démoulin Nicolas">
</act>
<act nom = "El Guerrab M'jid">
</act>
<act nom = "El Haïry Sarah">
</act>
<act nom = "Eliaou Jean-François">
</act>
<act nom = "Elimas Nathalie">
</act>
<act nom = "Errante Sophie">
</act>
<act nom = "Essayan Nadia">
</act>
<act nom = "Euzet Christophe">
</act>
<act nom = "Evrard José">
</act>
<act nom = "Fabre Catherine">
</act>
<act nom = "Fajgeles Élise">
</act>
<act nom = "Fanget Michel">
</act>
<act nom = "Fasquelle Daniel">
</act>
<act nom = "Faucillon Elsa">
</act>
<act nom = "Faure-Muntian Valéria">
</act>
<act nom = "Fauvergue Jean-Michel">
</act>
<act nom = "Fiat Caroline">
</act>
<act nom = "Fiévet Jean-Marie">
</act>
<act nom = "Florennes Isabelle">
</act>
<act nom = "Folliot Philippe">
</act>
<act nom = "Fontaine-Domeizel Emmanuelle">
</act>
<act nom = "Fontenel-Personne Pascale">
</act>
<act nom = "Forteza Paula">
</act>
<act nom = "Freschi Alexandre">
</act>
<act nom = "Fuchs Bruno">
</act>
<act nom = "Fugit Jean-Luc">
</act>
<act nom = "Gaillard Olivier">
</act>
<act nom = "Gaillot Albane">
</act>
<act nom = "Galbadon Grégory">
</act>
<act nom = "Gallerneau Patricia">
</act>
<act nom = "Garcia Laurent">
</act>
<act nom = "Gassilloud Thomas">
</act>
<act nom = "Gaultier Jean-Jacques">
</act>
<act nom = "Gauvain Raphaël">
</act>
<act nom = "Gayte Laurence">
</act>
<act nom = "Genetet Anne">
</act>
<act nom = "Gipson Séverine">
</act>
<act nom = "Girardin Éric">
</act>
<act nom = "Giraud Joël">
</act>
<act nom = "Givernet Olga">
</act>
<act nom = "Goasguen Claude">
</act>
<act nom = "Gomez-Bassac Valérie">
</act>
<act nom = "Gosselin Philippe">
</act>
<act nom = "Gouffier-Cha Guillaume">
</act>
<act nom = "Goulet Perrine">
</act>
<act nom = "Gouttefarde Fabien">
</act>
<act nom = "Grandjean Carole">
</act>
<act nom = "Granjus Florence">
</act>
<act nom = "Grau Romain">
</act>
<act nom = "Gregoire Olivia">
</act>
<act nom = "Grelier Jean-Carles">
</act>
<act nom = "Guerel Émilie">
</act>
<act nom = "Guerini Stanislas">
</act>
<act nom = "Guévenoux Marie">
</act>
<act nom = "Gérard Raphaël">
</act>
<act nom = "Hai Nadia">
</act>
<act nom = "Hammerer Véronique">
</act>
<act nom = "Hammouche Brahim">
</act>
<act nom = "Haury Yannick">
</act>
<act nom = "Hennion Christine">
</act>
<act nom = "Henriet Pierre">
</act>
<act nom = "Holroyd Alexandre">
</act>
<act nom = "Houbron Dimitri">
</act>
<act nom = "Houlié Sacha">
</act>
<act nom = "Huppé Philippe">
</act>
<act nom = "Hérin Danièle">
</act>
<act nom = "Iborra Monique">
</act>
<act nom = "Isaac-Sibille Cyrille">
</act>
<act nom = "Jacques Jean-Michel">
</act>
<act nom = "Jacquier-Laforge Élodie">
</act>
<act nom = "Janvier Caroline">
</act>
<act nom = "Jerretie Christophe">
</act>
<act nom = "Jolivet François">
</act>
<act nom = "Joncour Bruno">
</act>
<act nom = "Josso Sandrine">
</act>
<act nom = "Juanico Régis">
</act>
<act nom = "Julien-Laferrière Hubert">
</act>
<act nom = "Jumel Sébastien">
</act>
<act nom = "Kamowski Catherine">
</act>
<act nom = "Karamanli Marietta">
</act>
<act nom = "Kasbarian Guillaume">
</act>
<act nom = "Kerbarh Stéphanie">
</act>
<act nom = "Kerlogot Yannick">
</act>
<act nom = "Kervran Loïc">
</act>
<act nom = "Khattabi Fadila">
</act>
<act nom = "Khedher Anissa">
</act>
<act nom = "Kokouendo Rodrigue">
</act>
<act nom = "Krabal Jacques">
</act>
<act nom = "Krimi Sonia">
</act>
<act nom = "Kuric Aina">
</act>
<act nom = "Kuster Brigitte">
</act>
<act nom = "Kéclard-Mondésir Manuéla">
</act>
<act nom = "Laabid Mustapha">
</act>
<act nom = "Labaronne Daniel">
</act>
<act nom = "Lachaud Bastien">
</act>
<act nom = "Lagleize Jean-Luc">
</act>
<act nom = "Lainé Fabien">
</act>
<act nom = "Lakrafi Amélia">
</act>
<act nom = "Lang Anne-Christine">
</act>
<act nom = "Laqhila Mohamed">
</act>
<act nom = "Lardet Frédérique">
</act>
<act nom = "Larive Michel">
</act>
<act nom = "Larrivé Guillaume">
</act>
<act nom = "Larsonneur Jean-Charles">
</act>
<act nom = "Lasserre-David Florence">
</act>
<act nom = "Latombe Philippe">
</act>
<act nom = "Lavergne Pascal">
</act>
<act nom = "Lazaar Fiona">
</act>
<act nom = "Le Bohec Gaël">
</act>
<act nom = "Le Feur Sandrine">
</act>
<act nom = "Le Fur Marc">
</act>
<act nom = "Le Gac Didier">
</act>
<act nom = "Le Gendre Gilles">
</act>
<act nom = "Le Grip Constance">
</act>
<act nom = "Le Meur Annaïg">
</act>
<act nom = "Le Peih Nicole">
</act>
<act nom = "Le Pen Marine">
</act>
<act nom = "Le Vigoureux Fabrice">
</act>
<act nom = "Lebec Marie">
</act>
<act nom = "Leclabart Jean-Claude">
</act>
<act nom = "Leclerc Sébastien">
</act>
